---
- name: Update APT cache
  hosts: all
  become: True
  tasks:
    - name: Run apt update
      ansible.builtin.apt:
           update_cache: true
           cache_valid_time: 3600
           allow_unauthenticated: yes
           force_apt_get: true
     name:
        - htop
        - tmux
