---
- name: Update APT cache, upgrade, and install packages
  hosts: all
  become: True
  tasks:
    - name: Run apt update
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        allow_unauthenticated: yes

