---
- name: Run apt update
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    allow_unauthenticated: yes

- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist