---
- name: Run apt update
  ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        allow_unauthenticated: yes

- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
    state: latest

# - name: "Installing tools from Gems"
#   gem:
#     name: "{{ item }}"
#     state: latest
#   loop:
#     - logger
#     - stringio
#     - winrm
#     - builder
#     - erubi
#     - gssapi
#     - gyoku
#     - httpclient
#     - logging
#     - little-plugger
#     - nori
#     - rubyntlm
#     - winrm-fs
#     - evil-winrm