---
- name: Run apt update && Install packages
  import_tasks: apt-update.yml
  tags:
    - update
    - parrot

- name: Installing useful github repos
  import_tasks: github-repos.yml
  tags:
    - install
    - parrot

- name: Installing Kerbrute
  import_tasks: kerbrute.yml
  tags:
    - install
    - parrot

- name: Installing tmux
  import_tasks: configure_tmux.yml
  tags:
    - install
    - parrot

- name: Installing & Configure Audit Rules
  import_tasks: auditd.yml
  tags:
    - install
    - parrot

- name: Configure UFW
  import_tasks: ufw.yml
  tags:
    - install
    - parrot

- name: Configure burp
  import_tasks: burp.yml
  tags:
    - install
    - parrot

- name: Configure firefox
  import_tasks: firefox.yml
  tags:
    - install
    - parrot


- name: Configure terminal
  import_tasks: terminal.yml
  tags:
    - install
    - parrot